// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp2Iq1ii3CcYUEGna-JZM6g5xoYtpQcKo',
    appId: '1:61025513530:web:10bb31aca918a1c19a0503',
    messagingSenderId: '61025513530',
    projectId: 'journal-analyzer-3c319',
    authDomain: 'journal-analyzer-3c319.firebaseapp.com',
    storageBucket: 'journal-analyzer-3c319.firebasestorage.app',
    measurementId: 'G-RXQV6E4S9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd0D-E49MJlcAV7G6yIj0Ad0y1PAU3cxA',
    appId: '1:61025513530:android:7621fee8266ebea59a0503',
    messagingSenderId: '61025513530',
    projectId: 'journal-analyzer-3c319',
    storageBucket: 'journal-analyzer-3c319.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp2Iq1ii3CcYUEGna-JZM6g5xoYtpQcKo',
    appId: '1:61025513530:web:4aedf061de5bbab39a0503',
    messagingSenderId: '61025513530',
    projectId: 'journal-analyzer-3c319',
    authDomain: 'journal-analyzer-3c319.firebaseapp.com',
    storageBucket: 'journal-analyzer-3c319.firebasestorage.app',
    measurementId: 'G-J688J9L27P',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOhwx6PO9PeeYQY8jniUqxQS75xh-SxEk',
    appId: '1:61025513530:ios:953030cfb9b368aa9a0503',
    messagingSenderId: '61025513530',
    projectId: 'journal-analyzer-3c319',
    storageBucket: 'journal-analyzer-3c319.firebasestorage.app',
    androidClientId: '61025513530-m9dibdr9cas8tjsn6h1v5v0hik18783e.apps.googleusercontent.com',
    iosClientId: '61025513530-j6646vtk1u2s7trncucg5lkeimboccpe.apps.googleusercontent.com',
    iosBundleId: 'com.prm393.journalTrendAnalyzer',
  );
}
